language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
script:
- make publish github
env:
  global:
    secure: H7EVn38Au3B7PYGBLZJaTWAToo3kewPj93To3yGC+A5Ldy9S6Ok3vTA7cX2ZVZUNSUsY56x+meJt+jDdGYEfFJCLDWDH4slZ5WV6YcfNek7qN8JQoXynaSTT2A7V04+UgnQw8MFSkqxjdbXo2hzx27E2vGjL6Vd4uwop0ZR5AxbbgIjKY3QnD6kRikQyXvAyvIM2QaK/HiLn7Rry4rME+ecvkWedCZV4iXV9rDblIfQ1b/u4rfHLmg9BYPUIQp009EEd8kgL2IeyQzM7hg9DFj4TRU1ykJySz9NchbG3KGOjtrK/EQyhLAradpEU7QBETkGvIvOo/IKEyYYKv32LsjghXq6z46uQVYb6qauSXAYb50eVxIaEoHlXZjIxOl7Ly5rpzNlTG1rTKupItO99Rvy/jmTcAFBgVBzj8SkSBENIWoW99ilNKzF1Q3VQk+ojRD4vKWP2Ymqvit0DF9YidaGhPohCezwRxaQacTfPh+tCKQWh3ktNU+HMwSgj7ovjq1w9vkPzuY67ju28yK+Te0hKEo/7bPGhUfrsPL8tE9lfGXC2yalxrydQWClxbSt589QK8IBpcBl7+OKfEaA8Xq208RriqsUPn6p0w+yxGdIHi2iJJZ5lMgNXqAqAROAjgK7JF3FhElJHB+Lx74KLtsIpQCVDrNj9Nsywur331ZY=
